---

- name: Check for 'git' in System
  command: which git
  failed_when: false
  changed_when: false
  check_mode: false
  register: git_command_result

- name: Install Git via Apt (Debian)
  apt:
    name: git
    state: present
  when:
    - git_command_result.rc == 1
    - ansible_facts.os_family == "Debian"

- name: Update Git User Email
  git_config:
    name: user.email
    value: tristan.an.smith@gmail.com
    global: yes

- name: Update Git User Name
  git_config:
    name: user.name
    value: Tristan Smith
    global: yes

- name: Update Git Default Branch Name
  git_config:
    name: init.defaultBranch
    value: main
    global: yes