---

- name: Check current Python Version
  shell: cut -d' ' -f2 <<< "$(python3 --version)"
  register: current_python_version

- name: Set Python Version to Config
  command: pyenv install {{ python_version }}
  when: current_python_version.stdout != python_version
  ignore_errors: yes

- name: Link the new Python version to bin
  shell: |
   unlink /usr/local/bin/python3 &&
   ln -s ~/.pyenv/versions/{{ python_version }}/bin/python3 /usr/local/bin/python3
  when: current_python_version.stdout != python_version

- name: Uninstall old Python Version
  command: pyenv uninstall {{ current_python_version.stdout }}
  when: current_python_version.stdout != python_version


- name: Update Pip to latest with Pip
  easy_install:
    name: pip
    state: latest

- name: Install core Python Packages
  pip:
    name:
      - beautifulsoup4
      - numpy
      - pandas
      - requests
      - virtualenv
