---

- name: Check if Rust/cargo is already present.
  command: which cargo
  failed_when: false
  changed_when: false
  check_mode: false
  register: cargo_command_result

- name: Download Docker install convenience script.
  shell: "curl https://sh.rustup.rs -sSf | sh -s -- -y"
  changed_when: false

- name: Update Rust
  shell: rustup update