---

- name: Clone Oh My Zsh.
  shell: |
    sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

- name: Clone down and add autosuggestions ZSH plugin
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    clone: yes
    dest: {{ ansible_home_directory }}/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

- name: Clone down and add syntax highlighting ZSH plugin
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting
    clone: yes
    dest: {{ ansible_home_directory }}/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

- name: Clone down and add syntax highlighting ZSH plugin (Debian)
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting
    clone: yes
    dest: {{ ansible_home_directory }}/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
  when: ansible_facts.os_family == "Debian"

- name: Pull down personal ~/.zshrc file.
  uri: https://raw.github.com/lennee/environment-config/main/.zshrc
    dest: {{ ansible_home_directory }}/.zshrc
  when: ansible_facts.os_family == "Debian"
