---

- name: Configuring RPis
  hosts: raspberrypi
  vars:
    ansible_home_directory: /home/tristan

  pre_tasks:
    - name: Load Configuration (with defaults from example file)
      include_vars: "{{ item }}"
      loop:
        - config.yml

    - name: Ensure Apt is up to date
      apt:
        update_cache: true
        cache_valid_time: 3600

  tasks:

    - name: Install oh-my-zsh and download .zshrc
      import_tasks: ../tasks/zsh.yml